common/models/JmRepair.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "jm_repair".
 *
 * @property integer $id
 * @property string $job_no
 * @property string $car_license_no
 * @property string $car_license_province
 * @property integer $car_brand_id
 * @property integer $car_model_id
 * @property integer $car_series_id
 * @property integer $car_color_id
 * @property integer $car_type_id
 * @property integer $insurance_id
 * @property integer $insurance_type
 * @property integer $car_claim_type
 * @property string $contact_repair_date
 * @property string $contact_repair_firstname
 * @property string $contact_repair_lastname
 * @property string $contact_repair_tel
 * @property string $appoint_repair_date
 * @property integer $in_repair_emp
 * @property string $in_repair_date
 * @property string $in_repair_firstname
 * @property string $in_repair_lastname
 * @property string $in_repair_tel
 * @property integer $in_repair_type
 * @property string $appoint_sent_date
 * @property integer $sent_car_emp
 * @property string $sent_car_date
 * @property string $sent_car_firstname
 * @property string $sent_car_lastname
 * @property string $sent_car_tel
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 * * @property integer $first_claim_amt
* @property integer $other_amt
 *
 * @property TuUser $createdBy
 * @property TuUser $updatedBy
 * @property JmRepairClaim[] $jmRepairClaims
 */
class JmRepair extends \yii\db\ActiveRecord
{
    public $CarDetail;
    public $status_repair_name;
    public $labor_amt;
    public $part_amt;
    public $contact_repair_fullname;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jm_repair';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'value' => Yii::$app->user->getId(),
            ],
        ];
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['car_license_no'], 'required'],
            [['car_license_province', 'car_brand_id', 'car_model_id', 'car_series_id', 'car_color_id', 'payment_type', 'insurance_id', 'insurance_type', 'car_claim_type', 'in_repair_emp', 'in_repair_type', 'sent_car_emp', 'first_claim_amt', 'other_amt', 'created_by', 'updated_by', 'status_repair', 'status_invoice', 'num_repair', 'receive_money_by', 'car_type_id'], 'integer'],
            [['contact_repair_date', 'appoint_repair_date', 'in_repair_date', 'appoint_sent_date', 'sent_car_date', 'created_at', 'updated_at', 'receive_money_at'], 'safe'],
            [['other_amt_desc'], 'string'],
            [['job_no'], 'string', 'max' => 20],
            [['car_license_no'], 'string', 'max' => 10],
            [['contact_repair_firstname', 'contact_repair_lastname', 'contact_repair_tel', 'in_repair_firstname', 'in_repair_lastname', 'in_repair_tel', 'sent_car_firstname', 'sent_car_lastname', 'sent_car_tel'], 'string', 'max' => 50],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => TuUser::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => TuUser::className(), 'targetAttribute' => ['updated_by' => 'id']],
            [['receive_money_by'], 'exist', 'skipOnError' => true, 'targetClass' => TuUser::className(), 'targetAttribute' => ['receive_money_by' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                       => 'ID',
            'job_no'                   => 'Job No',
            'car_license_no'           => 'เลขที่ทะเบียนรถ',
            'car_license_province'     => 'จังหวัดทะเบียนรถ',
            'car_brand_id'             => 'ยี่ห้อรถ',
            'car_model_id'             => 'รุ่นรถ',
            'car_series_id'            => 'แบบรถ',
            'car_color_id'             => 'สีรถ',
            'car_type_id'              => 'ประเภทรถ',
            'payment_type'             => 'การชำระเงิน',
            'insurance_id'             => 'บริษัทประกันภัย',
            'insurance_type'           => 'ประเภทบริษัทประกัน',
            'car_claim_type'           => 'ประเภทรถซ่อม',
            'contact_repair_date'      => 'วันที่ติดต่อซ่อม',
            'contact_repair_firstname' => 'ชื่อผู้ติดต่อ',
            'contact_repair_lastname'  => 'สกุลผู้ติดต่อ',
            'contact_repair_tel'       => 'เบอร์ติดต่อ',
            'appoint_repair_date'      => 'วันที่นัดเข้าซ่อม',
            'in_repair_emp'            => 'พนักงานรับรถ',
            'in_repair_date'           => 'วันที่จอดซ่อม',
            'in_repair_firstname'      => 'ชื่อผู้นำรถเข้าซ่อม',
            'in_repair_lastname'       => 'นามสกุลผู้นำรถเข้าซ่อม',
            'in_repair_tel'            => 'เบอร์ติดต่อ',
            'in_repair_type'           => 'การจอดซ่อม',
            'appoint_sent_date'        => 'วันที่นัดรับรถซ่อมเสร็จ',
            'sent_car_emp'             => 'พนักงานส่งรถ',
            'sent_car_date'            => 'วันที่ส่งรถ',
            'sent_car_firstname'       => 'ชื่อผู้รับรถ',
            'sent_car_lastname'        => 'นามสกุลผู้รับรถ',
            'sent_car_tel'             => 'เบอร์ติดต่อ',
            'first_claim_amt'          => 'ค่า Ex.',
            'other_amt'                => 'เพิ่มเติม',
            'other_amt_desc'           => 'รายละเอียดเพิ่มเติม',
            'status_repair'            => 'สถานะซ่อม',
            'status_repair_name'       => 'สถานะซ่อม',
            'status_invoice'           => 'สถานะวางบิล',
            'created_at'               => Yii::t('app','Created At'),
            'created_by'               => Yii::t('app','Created By'),
            'updated_at'               => Yii::t('app','Updated At'),
            'updated_by'               => Yii::t('app','Updated By'),
            'CarDetail'                => 'ข้อมูลรถ',
            'num_repair'               => 'จำนวนชิ้นซ่อม',
            'receive_money_at'         => 'รับเงินเมื่อ',
            'receive_money_by'         => 'รับเงินโดย',
            'labor_amt'                => 'ค่าแรง',
            'part_amt'                 => 'ค่าอะไหล่',
            'contact_repair_fullname'  => 'ชื่อผู้ติดต่อ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarProvince()
    {
        return $this->hasOne(TuProvince::className(), ['id' => 'car_license_province']);
    }

    public function getCreatedBy()
    {
        return $this->hasOne(TuUser::className(), ['id' => 'created_by']);
    }

    public function getReceiveMoneyBy()
    {
        return $this->hasOne(TuUser::className(), ['id' => 'receive_money_by']);
    }

    public function getUpdatedBy()
    {
        return $this->hasOne(TuUser::className(), ['id' => 'updated_by']);
    }

    public function getCarBrand()
    {
        return $this->hasOne(TmBrand::className(), ['id' => 'car_brand_id']);
    }

    public function getCarModel()
    {
        return $this->hasOne(TmModel::className(), ['id' => 'car_model_id']);
    }

    public function getCarColor()
    {
        return $this->hasOne(TmColor::className(), ['id' => 'car_color_id']);
    }

    public function getInsurance()
    {
        return $this->hasOne(TuInsure::className(), ['id' => 'insurance_id']);
    }

    public function getRepairDetail()
    {
        return $this->hasMany(JmRepairDetail::className(), ['jm_repair_id' => 'id']);
    }

    public function getRepairPart()
    {
        return $this->hasMany(JmRepairPart::className(), ['jm_repair_id' => 'id']);
    }

    public function getJmRepairClaims()
    {
        return $this->hasMany(JmRepairClaim::className(), ['jm_repair_id' => 'id']);
    }

    public function getReciveCarEmp()
    {
        return $this->hasOne(TuUser::className(), ['id' => 'in_repair_emp']);
    }

    public function getCarType()
    {
        return $this->hasOne(TmCarType::className(), ['id' => 'car_type_id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            if ($this->job_no == '') {
                if (!in_array($this->status_repair, [1,5,6])) {
                    $this->job_no = Yii::$app->Utilities->getJobNumber();
                }
            }

            $this->contact_repair_date = (!empty($this->contact_repair_date))?date('Y-m-d',strtotime($this->contact_repair_date)):null;
            $this->appoint_repair_date = (!empty($this->appoint_repair_date))?date('Y-m-d',strtotime($this->appoint_repair_date)):null;
            $this->in_repair_date      = (!empty($this->in_repair_date))?date('Y-m-d',strtotime($this->in_repair_date)):null;
            $this->appoint_sent_date   = (!empty($this->appoint_sent_date))?date('Y-m-d',strtotime($this->appoint_sent_date)):null;
            $this->sent_car_date       = (!empty($this->sent_car_date))?date('Y-m-d',strtotime($this->sent_car_date)):null;
            $this->first_claim_amt     = (!empty($this->first_claim_amt))?str_replace(',', '', $this->first_claim_amt):null;  

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        $this->contact_repair_date     = (!empty($this->contact_repair_date))?date('d-m-Y',strtotime($this->contact_repair_date)):null;
        $this->appoint_repair_date     = (!empty($this->appoint_repair_date))?date('d-m-Y',strtotime($this->appoint_repair_date)):null;

common/models/TuUser.php
<?php
namespace common\models;

use Yii;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "tu_user".
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $firstname
 * @property string $lastname
 * @property string $nickname
 * @property int $comp_id
 * @property int $comp_br_id
 * @property int $dep_id
 * @property int $role_id
 * @property string $isactive
 * @property string $created_at
 * @property int $created_by
 * @property string $updated_at
 * @property int $updated_by
 */
class TuUser extends ActiveRecord implements IdentityInterface
{
    public $full_name;
    public $auth_key;
    public $password_hash;
    public $password_reset_token;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tu_user';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'value' => Yii::$app->user->getId(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username'], 'required'],
            [['comp_id', 'comp_br_id', 'dep_id', 'role_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at', 'isactive'], 'safe'],
            [['username'], 'string', 'max' => 30],
            [['password','auth_key'], 'string', 'max' => 50],
            [['firstname', 'lastname', 'password_hash', 'password_reset_token'], 'string', 'max' => 150],
            [['nickname'], 'string', 'max' => 100],
            [['username'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => 'Username',
            'password' => 'Password',
            'full_name' => 'ชื่อ-นามสกุล',
            'firstname' => 'ชื่อ',
            'lastname' => 'นามสกุล',
            'nickname' => 'ชื่อเล่น',
            'comp_id' => 'บริษัท',
            'comp_br_id' => 'สาขา',
            'dep_id' => 'หน่วยงาน',
            'role_id' => 'หน้าที่',
            'isactive' => Yii::t('app', 'Isactive'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Update By'),
        ];
    }

    public function getComp()
    {
        return $this->hasOne(TuComp::className(), ['id' => 'comp_id']);
    }

    public function getCompBr()
    {
        return $this->hasOne(TuCompBr::className(), ['id' => 'comp_br_id']);
    }

    public function getDep()
    {
        return $this->hasOne(TuDep::className(), ['id' => 'dep_id']);
    }

    public function getRole()
    {
        return $this->hasOne(TuRole::className(), ['id' => 'role_id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert))
        {
            if ($this->isNewRecord) {
                $this->password = md5($this->password);
            }

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        $this->full_name = $this->firstname.' '.$this->lastname.'('.$this->nickname.')';

        parent::afterFind();
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'isactive' => 'Y']);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'isactive' => 'Y']);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return ($password == $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/views/billing/_print-billing-repair-select.php
<div class="layout_page">
<?php 
$intPage        = 0;
$intNumPrint    = count($models);
foreach ($models as $model) {
    $intPage++;
?>
<table width="100%">
    <tr>
        <!-- <td style="padding: 10px;" align="right"><img src="<?php //echo Yii::getAlias('@web').'/imgs/logo_comp.png' ?>" style="margin-top: 20px;"></td> -->
        <td>
            <center>
            <h1><?php echo Yii::$app->user->identity->comp->comp_name; ?></h1>
            <br>
            <p class="pdf_company_address">
                <?php echo Yii::$app->user->identity->compBr->br_name; ?>
                <?php echo Yii::$app->user->identity->compBr->br_addr; ?>
            </p>
            <br>
            <!-- <p class="pdf_company_address">
                โทร <?php //echo Yii::$app->user->identity->compBr->br_telno; ?>
                แฟกซ์ <?php //echo Yii::$app->user->identity->compBr->br_faxno; ?>
                E-mail <?php //echo Yii::$app->user->identity->compBr->br_email; ?>
            </p> -->
            </center>
        </td>
    </tr>
</table>
<table width="100%">
    <tr>
        <td style="padding: 10px;" width="100%"><h3><center>ใบกำกับภาษี/ใบเสร็จรับเงิน</center></h3></td>
    </tr>
</table>
<table width="100%">
    <tr>
        <td width="75%" style="border: 1px solid #000;padding-top: 3px;padding-bottom: 20px;" >
            <table width="100%" border="0" cellpadding="2" cellspacing="0">
                <tr>
                    <td width="16%" style="font-weight: bold;padding: 5px;vertical-align: top;">นามผู้ซื้อ</td>
                    <td width="84%" style="padding: 5px;vertical-align: top;"><?php echo ($model->jmRepair->insurance)?$model->jmRepair->insurance->insure_name:''; ?></td>
                </tr>
                <tr>
                    <td style="font-weight: bold;padding: 5px;vertical-align: top;">ที่อยู่</td>
                    <td style="padding: 5px;vertical-align: top;"><?php echo ($model->jmRepair->insurance)?nl2br($model->jmRepair->insurance->insure_addr):''; ?></td>
                </tr>
            </table>
        </td>
        <td style="padding: 5px;vertical-align: top;" width="25%">
            <center>
                <h4>เลขที่ <?php echo $model->invoice_no; ?></h4>
                <br>
                เลขประจำตัวผู้เสียภาษี
                <br><br>
                <?php echo Yii::$app->user->identity->compBr->br_tax_id; ?>
                <br><br>
                <?php echo date('d/m/Y', strtotime($model->billing_date)); ?>
            </center>
        </td>
    </tr>
</table>
<table class="table_bordered" style="margin-top: 10px;" width="100%" border="0" cellpadding="2" cellspacing="0">
    <thead>
    <tr>
        <th style="padding: 10px 5px;" width="10%"><center>ลำดับที่</center></th>
        <th style="padding: 10px 5px;" width="50%"><center>รายการ</center></th>
        <th style="padding: 10px 5px;" width="20%"><center>จำนวนหน่วย</center></th>
        <th style="padding: 10px 5px;" width="20%"><center>จำนวนเงิน</center></th>
    </tr>
    </thead>
    <?php
            if ($model->repair_amt > 0) {
                $intSum = ($model->repair_amt/107)*100;
    ?>
                <tr>
                    <td style="padding: 10px;"><center>1</center></td>
                    <td style="padding: 10px;">ค่าแรงซ่อมรถ <?php echo $model->jmRepair->car_license_no;?> <?php echo (!empty($model->jmRepair->carProvince))?$model->jmRepair->carProvince->province_name:'';?></td>
                    <td style="padding: 10px;"><center>1</center></td>
                    <td style="padding: 10px;text-align: right;"><?php echo number_format($intSum, 2);?></td>
                </tr>
    <?php }
        // if (!empty($model->jmRepair->insurance) && in_array($model->jmRepair->insurance->id, [20, 34, 36])) {
    ?>
        <tr>
            <td style="padding: 10px;">&nbsp;</td>
            <td style="padding: 10px;">เคลมเลขที่ <?php echo $model->claim_no ?></td>
            <td style="padding: 10px;">&nbsp;</td>
            <td style="padding: 10px;">&nbsp;</td>
        </tr>
    <?php
        // }
        for ($i=1; $i <= 4; $i++) {
    ?>
        <tr>
            <td style="padding: 10px;">&nbsp;</td>
            <td style="padding: 10px;">&nbsp;</td>
            <td style="padding: 10px;">&nbsp;</td>
            <td style="padding: 10px;">&nbsp;</td>
        </tr>
    <?php }

        $intVat = ($intSum * 7)/100;
        $intNet = $intSum + $intVat;
    ?>
    <tr>
        <td colspan="3" style="padding: 10px;text-align: right;font-weight: bold;">รวมราคาทั้งสิ้น</td>
        <td style="padding: 10px;border:1px solid;text-align: right;"><?php echo number_format($intSum, 2);?></td>
    </tr>
    <tr>
        <td colspan="3" style="padding: 10px;text-align: right;font-weight: bold;">จำนวนภาษีมูลค่าเพิ่ม</td>
        <td style="padding: 10px;border:1px solid;text-align: right;"><?php echo number_format($intVat, 2);?></td>
    </tr>
    <tr>
        <td colspan="3" style="padding: 10px;text-align: right;font-weight: bold;">จำนวนเงินรวมทั้งสิ้น</td>
        <td style="padding: 10px;border:1px solid;text-align: right;"><?php echo number_format($intNet, 2);?></td>
    </tr>
</table>
<table width="100%" style="margin-top: 20px;">
    <tr>
        <td colspan="4" style="padding: 10px;text-align: left;font-weight: bold;padding-left: 50px;">(<?php echo Yii::$app->Helpers->thaiAmount(number_format($intNet,2)); ?>)</td>
    </tr>
</table>
<table width="100%" style="margin-top: 50px;">
    <tr>
        <td width="5%">&nbsp;</td>
        <td width="35%"><center>.........................................................................</center></td>
        <td width="20%">&nbsp;</td>
        <td width="35%"><center>.........................................................................</center></td>
        <td width="5%">&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td style="font-size: 16px;"><center>ผู้รับสินค้า</center></td>
        <td>&nbsp;</td>
        <td style="font-size: 16px;"><center>ผู้ได้รับมอบอำนาจ/ผู้รับเงิน</center></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><center>....................../....................../......................</center></td>
        <td>&nbsp;</td>
        <td><center>.......<span style="font-size: 16px;"><?php echo date('d')?></span>........./..........<span style="font-size: 16px;"><?php echo date('m')?></span>........./..........<span style="font-size: 16px;"><?php echo date('Y')?></span>..........</center></td>
        <td>&nbsp;</td>
    </tr>
</table>

<?php 
    if ($intPage < $intNumPrint) {echo '<pagebreak>';}
}
?>
</div>

backend/views/billing/_search-billing-insurance.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
?>

<?php
$layout = <<< HTML
    {input1}
    {separator}
    {input2}
    <span class="input-group-addon kv-date-remove">
        <i class="fa fa-remove"></i>
    </span>
HTML;

$form = ActiveForm::begin([
    'action' => ['billing-by-insurance'],
    'method' => 'post',
    // 'type' => ActiveForm::TYPE_HORIZONTAL, //TYPE_HORIZONTAL
    // 'formConfig' => ['labelSpan' => 4, 'deviceSize' => ActiveForm::SIZE_SMALL],
    //SIZE_TINY = 'xs',SIZE_SMALL = 'sm',SIZE_MEDIUM = 'md',SIZE_LARGE = 'lg'
]);
?>

<div class="jm-repair-search">

    <div class="box box-default">
    <div class="box-header with-border"><i class="fa fa-search"></i></div>

    <div class="box-body">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <?php echo $form->field($model, 'insurance_id')->widget(Select2::classname(), [
                    'data'=> Yii::$app->Utilities->getItemInsureName(),
                    ]);
                ?>
            </div>
            <div class="col-sm-6 col-md-4">
                <?php
                    echo $form->field($model, 'dateBillingStart')->widget(DatePicker::classname(), [
                        'type' => DatePicker::TYPE_RANGE,
                        'attribute2' => 'dateBillingEnd',
                        'separator' => 'ถึง',
                        'layout' => $layout,
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd-mm-yyyy'
                        ]
                    ])->label('วันที่วางบิล');
                ?>
            </div>
        </div>
    </div>

    </div>

    <div class="box-footer">
        <div class="col-md-12 text-right">
            <?php echo Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default', 'onClick'=>'ClearSearch();']) ?>
            <?php echo Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    </div>

</div>

<?php echo $form->field($model, 'billing_status')->hiddenInput()->label(false); ?>

<?php ActiveForm::end(); ?>

<script>
    function ClearSearch()
    {
        $('#jmrepairclaimsearch-insurance_id').val('');
        $('#jmrepairclaimsearch-dateBillingStart').val('');
        $('#jmrepairclaimsearch-datebillingend').val('');
    }
</script>

backend/views/billing/update-billing.php
<?php
use yii\helpers\Html;
use kartik\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin([
    'id' => 'form-update-billing',
    'type' => ActiveForm::TYPE_VERTICAL, //TYPE_HORIZONTAL
    //'formConfig' => ['labelSpan' => 3, 'deviceSize' => ActiveForm::SIZE_SMALL],
    //SIZE_TINY = 'xs',SIZE_SMALL = 'sm',SIZE_MEDIUM = 'md',SIZE_LARGE = 'lg'
]); ?>
<div class="row">
	<div class="col-md-12">
		<h3><span class="label label-default">Job No : <?php echo $model->jmRepair->job_no; ?></span></h3>
	</div>
	<div class="col-md-6">
		<?php echo $form->field($model, 'repair_amt')->textInput(); ?>
	</div>
	<div class="col-md-6">
		<?php echo $form->field($model, 'part_amt')->textInput(); ?>
	</div>
</div>
<?php echo $form->field($model, 'id')->hiddenInput()->label(false); ?>
<?php ActiveForm::end(); ?>