common/models/RepaircarController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use kartik\mpdf\Pdf;

use common\models\JmRepair;
use common\models\JmRepairSearch;
use common\models\JmRepairDetail;
use common\models\JmRepairPart;
use common\models\JmRepairClaim;

/**
 * Site controller
 */
class RepaircarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'create', 'update', 'view', 'add-repair-detail', 'delete-repair-detail', 'add-repair-part', 'delete-repair-part', 'view-recive-repair', 'print-recive-repair', 'add-repair-claim', 'delete-repair-claim', 'list-order-job', 'calendar-repair', 'add-repair-appoint', 'report-repair-car', 'view-repair-appoint', 'sent-repair-car', 'save-receive-money'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel  = new JmRepairSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['status_repair' => [2,3]]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSentRepairCar()
    {
        $searchModel  = new JmRepairSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['status_repair' => [4]]);

        return $this->render('sent-repair-car', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionReportRepairCar()
    {
        $searchModel = new JmRepairSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['<>','status_repair', 1]);

        return $this->render('report-repair-car', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single JmRepair model.
     * @param integer $id
     * @return mixed
     */
    public function actionView()
    {
        $dataPost = Yii::$app->request->post();
        return $this->renderAjax('view', [
            'model' => $this->findModel($dataPost['id']),
        ]);
    }

    public function actionCalendarRepair()
    {
        $events      = array();
        $model       = new JmRepair();
        $searchModel = new JmRepairSearch();
        $modelRepair = $searchModel->queryCarInRepair();
        // echo '<pre>';print_r($modelRepair);echo '</pre>';exit;

        foreach ($modelRepair as $valData) {
            $Event        = new \yii2fullcalendar\models\Event();
            $Event->id    = $valData->id;
            $Event->title = $valData->car_license_no.' จำนวน '.intval($valData->num_repair).' ชิ้น';
            $Event->start = date('Y-m-d',strtotime($valData->appoint_repair_date));
            $events[]     = $Event;
        }

        $modelSend = $searchModel->queryCarAppointSend();
        foreach ($modelSend as $valSend) {
            $Event        = new \yii2fullcalendar\models\Event();
            $Event->color = '#ff1a1a';
            $Event->id    = $valSend->id;
            $Event->title = $valSend->car_license_no.' นัดส่ง';
            $Event->start = date('Y-m-d',strtotime($valSend->appoint_sent_date));
            $events[]     = $Event;
        }

        return $this->render('calendar-repair', [
            'model'=>$model,
            'events'=>$events,
        ]);
    }

    public function actionAddRepairAppoint()
    {
        $dataPost = Yii::$app->request->post();
        if (!empty($dataPost)) {
            $model                           = new JmRepair();
            $model->appoint_repair_date      = $dataPost['appoint_date'];
            $model->car_license_no           = $dataPost['appoint_license_no'];
            $model->contact_repair_firstname = $dataPost['appoint_first_name'];
            $model->contact_repair_lastname  = $dataPost['appoint_last_name'];
            $model->contact_repair_tel       = $dataPost['appoint_telno'];
            $model->insurance_id             = $dataPost['repair_insure'];
            $model->num_repair               = $dataPost['num_repair'];
            $model->status_repair            = '1';
            if ($model->save()) {
                return true;
            } else {
                return false;
            }
        }
    }

    public function actionViewRepairAppoint()
    {
        $dataPost = Yii::$app->request->post();
        $model    = JmRepairClaim::find()->where(['id'=>$dataPost['id']])->one();
        return $this->renderAjax('view-repair-appoint', [
            'model' => $model,
        ]);
    }

    public function actionViewReciveRepair($id)
    {
        return $this->render('view-recive-repair', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionPrintReciveRepair($id)
    {
        $model        =  $this->findModel($id);
        $content      = $this->renderPartial('_print-recive-repair', ['model' => $model]);
        $strTitleName = 'ใบรับรถเข้าซ่อม';
        $strFileName  = 'receipt_car_'.$model->job_no;
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' =>Pdf::FORMAT_A4,
            'marginLeft' => 3,
            'marginRight' => 2,
            'marginTop' => 1,
            'marginBottom' => false,
            'marginHeader' => false,
            'marginFooter' => 1,
            // portrait orientation //ORIENT_LANDSCAPE, ORIENT_PORTRAIT
            'orientation' => Pdf::ORIENT_LANDSCAPE,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@backend/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-2{font-size:22px}',
             // set mPDF properties on the fly
            'options' => [
                'title' => $strTitleName,
            ],
             // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>false,
                'SetFooter'=>false,
            ],
            'filename' => $strFileName.'.pdf',
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
        // return $this->renderPartial('_pdf-print-request-receipt', ['model' => $model]);
    }

    /**
     * Creates a new JmRepair model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new JmRepair();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view-recive-repair', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing JmRepair model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model       = $this->findModel($id);
        $modelDetail = new JmRepairDetail();
        $modelPart   = new JmRepairPart();
        $modelClaim  = new JmRepairClaim();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $listRepairDetail = $this->findListRepairDetail($id);
            $listRepairPart   = $this->findListRepairPart($id);
            $listRepairClaim  = $this->findListRepairClaim($id);
            return $this->render('update', [
                'model'            => $model,
                'modelDetail'      => $modelDetail,
                'listRepairDetail' => $listRepairDetail,
                'modelPart'        => $modelPart,
                'listRepairPart'   => $listRepairPart,
                'modelClaim'       => $modelClaim,
                'listRepairClaim'  => $listRepairClaim,
            ]);
        }
    }

    /**
     * Deletes an existing JmRepair model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the JmRepair model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return JmRepair the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

common/models/TuUser.php
<?php
namespace common\models;

use Yii;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "tu_user".
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $firstname
 * @property string $lastname
 * @property string $nickname
 * @property int $comp_id
 * @property int $comp_br_id
 * @property int $dep_id
 * @property int $role_id
 * @property string $isactive
 * @property string $created_at
 * @property int $created_by
 * @property string $updated_at
 * @property int $updated_by
 */
class TuUser extends ActiveRecord implements IdentityInterface
{
    public $full_name;
    public $auth_key;
    public $password_hash;
    public $password_reset_token;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tu_user';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'value' => Yii::$app->user->getId(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username'], 'required'],
            [['comp_id', 'comp_br_id', 'dep_id', 'role_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at', 'isactive'], 'safe'],
            [['username'], 'string', 'max' => 30],
            [['password','auth_key'], 'string', 'max' => 50],
            [['firstname', 'lastname', 'password_hash', 'password_reset_token'], 'string', 'max' => 150],
            [['nickname'], 'string', 'max' => 100],
            [['username'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => 'Username',
            'password' => 'Password',
            'full_name' => 'ชื่อ-นามสกุล',
            'firstname' => 'ชื่อ',
            'lastname' => 'นามสกุล',
            'nickname' => 'ชื่อเล่น',
            'comp_id' => 'บริษัท',
            'comp_br_id' => 'สาขา',
            'dep_id' => 'หน่วยงาน',
            'role_id' => 'หน้าที่',
            'isactive' => Yii::t('app', 'Isactive'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Update By'),
        ];
    }

    public function getComp()
    {
        return $this->hasOne(TuComp::className(), ['id' => 'comp_id']);
    }

    public function getCompBr()
    {
        return $this->hasOne(TuCompBr::className(), ['id' => 'comp_br_id']);
    }

    public function getDep()
    {
        return $this->hasOne(TuDep::className(), ['id' => 'dep_id']);
    }

    public function getRole()
    {
        return $this->hasOne(TuRole::className(), ['id' => 'role_id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert))
        {
            if ($this->isNewRecord) {
                $this->password = md5($this->password);
            }

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        $this->full_name = $this->firstname.' '.$this->lastname.'('.$this->nickname.')';

        parent::afterFind();
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'isactive' => 'Y']);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'isactive' => 'Y']);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return ($password == $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/views/repaircar/_form-repair-detail.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="row">
	<div class="col-sm-4 col-md-4">
		<?php echo $form->field($modelDetail, 'repair_name')->textInput() ?>
	</div>
	<!-- <div class="col-sm-2 col-md-2">
		<?php //echo $form->field($modelDetail, 'repair_price')->textInput() ?>
	</div> -->
	<div class="col-sm-4 col-md-4">
		<?php echo $form->field($modelDetail, 'repair_remark')->textInput() ?>
	</div>
	<div class="col-sm-2 col-md-2" style="margin-top: 25px;">
		<?php echo Html::button('<i class="fa fa-plus"></i> '.Yii::t('app', 'Add Repair'), ['class' => 'btn btn-warning', 'onClick'=>'addRepairDetail();']) ?>
	</div>
</div>

<div class="row" id="list-repair-detail">
<?php echo $this->render('_list-repair-detail', ['listRepairDetail' => $listRepairDetail]); ?>
</div>

<script>
	function addRepairDetail()
	{
		if ($("#jmrepairdetail-repair_name").val() == '') {
			Swal.fire({
				title: 'กรุณาระบุข้อมูลรายการซ่อม!',
				icon: 'error'
			});
		} else {
			$.post( "<?php echo Url::to(['/repaircar/add-repair-detail']);?>", {
				repair_id:<?php echo $model->id;?>,
				repair_name:$("#jmrepairdetail-repair_name").val(),
				// repair_price:$("#jmrepairdetail-repair_price").val(),
				repair_remark:$("#jmrepairdetail-repair_remark").val()
			}, function(data) {
			  $("#list-repair-detail").html(data);
			});
			//RESET VALUES
			resetInputRepairDetail();
		}
	}

	function deleteRepairDetail(id)
	{
		$.post( "<?php echo Url::to(['/repaircar/delete-repair-detail']);?>", {id:id}, function(data) {
		  	$("#list-repair-detail").html(data);
		});
	}

	function resetInputRepairDetail()
	{
		$("#jmrepairdetail-repair_name").val('');
		// $("#jmrepairdetail-repair_price").val('');
		$("#jmrepairdetail-repair_remark").val('');
	}
</script>

backend/views/repaircar/_print-recive-repair.php
<div class="layout_page">
<table width="100%">
    <tr>
        <td style="padding: 10px;"><img src="<?php echo Yii::getAlias('@web').'/imgs/logo_comp.png' ?>" style="margin-top: 20px;"></td>
        <td><center>
            <h2><?php echo Yii::$app->user->identity->comp->comp_name; ?></h2>
            <h3><?php echo Yii::$app->user->identity->comp->comp_name_en; ?></h3>
            <h4><?php echo Yii::$app->user->identity->compBr->br_addr; ?></h4>
            <h4>
                โทร <?php echo Yii::$app->user->identity->compBr->br_telno; ?>
                แฟกซ์ <?php echo Yii::$app->user->identity->compBr->br_faxno; ?>
                E-Mail <?php echo Yii::$app->user->identity->compBr->br_email; ?>
                </h4></center>
        </td>
    </tr>
</table>
<table width="100%" style="margin: 25px 0px 25px 0px;">
    <tr>
        <td width="20%">&nbsp;</td>
        <td width="60%"><center><h2><?php echo Yii::t('app', 'Recive Repair Car'); ?></h2></center></td>
        <td width="20%"><h4>เลขที่ <?php echo $model->job_no; ?></h4></td>
    </tr>
</table>
<table width="100%">
    <tr>
        <td class="col-md-8">
            <table width="100%" style="border: solid 1px;">
                <tr>
                    <th width="25%" style="padding: 10px;text-align: left;">ชื่อลูกค้า</th>
                    <td width="75%" style="padding: 10px;"><?php echo $model->in_repair_firstname.' '.$model->in_repair_lastname; ?></td>
                </tr>
                <tr>
                    <th width="25%" style="padding: 10px;text-align: left;">เบอร์ติดต่อ</th>
                    <td width="75%" style="padding: 10px;"><?php echo $model->in_repair_tel; ?></td>
                </tr>
                <tr>
                    <th width="25%" style="padding: 10px;text-align: left;">ทะเบียนรถ</th>
                    <td width="75%" style="padding: 10px;"><?php echo $model->car_license_no; ?></td>
                </tr>
                <tr>
                    <th width="25%" style="padding: 10px;text-align: left;">รถ</th>
                    <td width="75%" style="padding: 10px;"><?php echo $model->CarDetail; ?></td>
                </tr>
                <tr>
                    <th width="25%" style="padding: 10px;text-align: left;">ประกัน</th>
                    <td width="75%" style="padding: 10px;"><?php echo (!empty($model->insurance))?$model->insurance->insure_name:''; ?></td>
                </tr>
            </table>
        </td>
        <td class="col-md-4" style="border: solid 1px;">
            <table width="100%">
                <tr>
                    <th class="col-md-5" style="padding: 10px;text-align: left;">วันที่รถเข้าซ่อม</th>
                    <td class="col-md-7" style="padding: 10px;"><?php echo $model->in_repair_date; ?></td>
                </tr>
                <tr>
                    <th class="col-md-5" style="padding: 10px;text-align: left;">วันที่นัดรับรถ</th>
                    <td class="col-md-7" style="padding: 10px;"><?php echo $model->appoint_sent_date; ?></td>
                </tr>
                <tr>
                    <th class="col-md-5" style="padding: 10px;text-align: left;">ค่าเสียหายส่วนแรก</th>
                    <td class="col-md-7" style="padding: 10px;"><?php echo number_format($model->first_claim_amt, 2); ?></td>
                </tr>
                <tr>
                    <th class="col-md-5" style="padding: 10px;text-align: left;">เพิ่มเติม</th>
                    <td class="col-md-7" style="padding: 10px;"><?php echo number_format($model->other_amt, 2); ?></td>
                </tr>
                <tr>
                    <th colspan="2" style="padding: 10px;">โปรดนำใบเอกสารนี้มาในวันรับรถ</th>
                </tr>
            </table>
        </td>
    </tr>
</table>
<table width="100%" style="margin-top: 100px;">
    <tr>
        <td width="10%"></td>
        <td width="35%" style="border-bottom: dotted;">&nbsp;</td>
        <td width="10%"></td>
        <td width="35%" style="border-bottom: dotted;">&nbsp;</td>
        <td width="10%"></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td style="padding: 10px 0px 10px 0px;"><center>(<?php echo $model->in_repair_firstname.' '.$model->in_repair_lastname; ?>)</center></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td><center>ผู้ตรวจรับรถ</center></td>
        <td></td>
        <td><center>ลูกค้านำรถเข้าซ่อม</center></td>
        <td></td>
    </tr>
</table>
<table width="100%" style="margin-top: 30px;">
    <tr>
        <td width="10%"></td>
        <td width="35%" style="border-bottom: dotted;">&nbsp;</td>
        <td width="10%"></td>
        <td width="35%" style="border-bottom: dotted;">&nbsp;</td>
        <td width="10%"></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td</td>>(<?php echo $model->in_repair_firstname.' '.$model->in_repair_lastname; ?>)</td>
        <td></td>
    </tr>
</table>
<table width="100%" style="margin-top: 40px;">
    <tr>
        <td colspan="5"><center>กรุณานำทรัพย์สินมีค่าออก-พระเครื่อง-อื่นๆ ก่อนนำรถเข้าซ่อม บริษัทจะไม่รับผิดชอบใดๆ ทั้งสิ้นหากเกิดการสูญเสีย</center></td>
    </tr>
</table>
</div>
</div>

backend/views/repaircar/calendar-repair.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;

use kartik\widgets\ActiveForm;
use kartik\widgets\DatePicker;
use kartik\widgets\Select2;


$this->title = Yii::t('app','Calendar Repair Cars');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'List Repair Cars'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

backend\assets\AppointmentAsset::register($this);
?>

<div class="box box-success">
    <div class="box-header with-border">
        <i class="fa fa-calendar"></i>
    </div>
    <div class="box-body">
		<div class="row">
			<div class="col-md-12">
				<div id="calendar"></div>
			</div>
		</div>
	</div>
</div>

<?php $form = ActiveForm::begin([
	'id'=>'frm-add-appoint-repair',
    'type' => ActiveForm::TYPE_VERTICAL, //TYPE_HORIZONTAL
    //'formConfig' => ['labelSpan' => 3, 'deviceSize' => ActiveForm::SIZE_SMALL],
    //SIZE_TINY = 'xs',SIZE_SMALL = 'sm',SIZE_MEDIUM = 'md',SIZE_LARGE = 'lg'
]); ?>

<div class="modal fade" tabindex="-1" role="dialog" id="model-edit">
	<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">Modal title</h4>
		</div>
		<div class="modal-body">
			<div class="row">

				<div class="col-sm-6 col-md-6">
			        <?php echo $form->field($model, 'appoint_repair_date')->textInput(['maxlength' => true, 'readOnly'=>true]) ?>
			    </div>

	            <div class="col-sm-6 col-md-6">
	                <?php echo $form->field($model, 'car_license_no')->textInput(['maxlength' => true, 'placeholder'=>'ตัวอย่าง กก-999']) ?>
	            </div>

	            <div class="col-sm-6 col-md-6">
                    <?php echo $form->field($model, 'contact_repair_firstname')->textInput(['maxlength' => true]) ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php echo $form->field($model, 'contact_repair_lastname')->textInput(['maxlength' => true]) ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php echo $form->field($model, 'contact_repair_tel')->textInput(['maxlength' => true]) ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php echo $form->field($model, 'insurance_id')->widget(Select2::classname(), [
                        'data'=> Yii::$app->Utilities->getItemInsureName(),
                        ]);
                    ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php echo $form->field($model, 'num_repair')->textInput(['maxlength' => true]) ?>
                </div>
			</div>
		</div>
		<div class="modal-footer">
			<?php echo Html::button(Yii::t('app','Close'), ['class'=>'btn btn-default', 'data-dismiss'=>'modal']); ?>
			<?php echo Html::button(Yii::t('app','Save'), ['class'=>'btn btn-success', 'onClick'=>'SaveDayAppoint();']); ?>
		</div>
	</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php ActiveForm::end(); ?>

<div class="modal fade" tabindex="-1" role="dialog" id="modelView">
	<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">รายละเอียด</h4>
		</div>
		<div class="modal-body" id="modal-body-view"></div>
		<!-- <div class="modal-footer">
			<?php echo Html::button(Yii::t('app','Close'), ['class'=>'btn btn-default', 'data-dismiss'=>'modal']); ?>
			<?php echo Html::button(Yii::t('app','Save'), ['class'=>'btn btn-success', 'onClick'=>'SaveDayAppoint();']); ?>
		</div> -->
	</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
	var url_list_data = "<?php echo Url::to(['/repaircar/list-calendar-repair']);?>";
	var url_view_data = "<?php echo Url::to(['/repaircar/view-repair-appoint']);?>";
	function SaveDayAppoint(){
		if ($('#appoint_license_no').val() == '') {
			alert('กรุณาระบุ เลขทะเบียนรถ');
		} else if ($('#appoint_first_name').val() == '') {
			alert('กรุณาระบุ ชื่อผู้ติดต่อ');
		} else {
			$.post( "<?php echo Url::to(['/repaircar/add-repair-appoint']);?>", {
				appoint_date:$("#jmrepair-appoint_repair_date").val(),
				appoint_license_no:$("#jmrepair-car_license_no").val(),
				appoint_first_name:$("#jmrepair-contact_repair_firstname").val(),
				appoint_last_name:$("#jmrepair-contact_repair_lastname").val(),
				appoint_telno:$("#jmrepair-contact_repair_tel").val(),
				repair_insure:$("#jmrepair-insurance_id").val(),
				num_repair:$("#jmrepair-num_repair").val(),
			}, function(data) {
			  alert('บันทึกข้อมูลเรียบร้อย');
			  $("#model-edit").modal("hide");
			  window.location.reload();
			});
		}
	}

	function ViewAppoint(id){
			$.post( "<?php echo Url::to(['/repaircar/view-repair-appoint']);?>", {
				id:id,
			}, function(data) {
				$("#modal-body-view").html(data);
				$("#modelView").modal("show");
			});
	}
</script>